version: '2'

services:
  proxy:
    build: .
    ports:
      - 443:443
    volumes:
      - ./start.sh:/usr/local/openresty/start.sh
    environment:
      - OID_SESSION_SECRET=623q4hR325t36VsCD3g567922IC0073T
      - OID_SESSION_CHECK_SSI=off
      - OID_SESSION_NAME=oidc_auth

      - OID_REDIRECT_PATH=/redirect_uri
      - OID_DISCOVERY=http://192.168.99.100:8080/auth/realms/master/.well-known/openid-configuration
      - OID_CLIENT_ID=proxy
      - OID_CLIENT_SECRET=71f09675-bf22-4082-8807-1d7635527554

      - PROXY_HOST=192.168.1.4
      - PROXY_PORT=8383
      - PROXY_PROTOCOL=http
    network_mode: bridge

  keycloak:
    image: jboss/keycloak
    ports:
      - 8080:8080
    environment:
    - KEYCLOAK_USER=admin
    - KEYCLOAK_PASSWORD=admin
    - KEYCLOAK_IMPORT=/tmp/realm.json

    volumes:
      - ./keycloak/realm.json:/tmp/realm.json
      - ./keycloak/keycloak-bg.png:/opt/jboss/keycloak/themes/keycloak/login/resources/img/keycloak-bg.png

    network_mode: bridge
